# WorldQL Connection Details
worldql:
  host: '127.0.0.1'
  push-port: 5555

redis:
  host: 'localhost'
  port: 6379

slice-mode: true
num-servers: 3
world-diameter: 1000
slice-width: 100
dmz-size: 10
starting-port: 25580

inventory-sync-only: false

# See players on other servers?
ghosts: true
# Disable this if you want to replace Mammoth's sync with MySQLPlayerDataBridge.
sync-player-inventory: true

# Client (self) Host
host: '127.0.0.1'