# WorldQL Connection Details
worldql:
  host: '127.0.0.1'
  push-port: 5555

redis:
  host: 'localhost'
  port: 6379

slice-mode: true
num-servers: 3
world-diameter: 1000
slice-width: 100
dmz-size: 10
starting-port: 25580

# See players on other servers?
ghosts: true

# Disable these if you want to use Mammoth with MySQLPlayerDataBridge.
sync-player-inventory: true
sync-player-health-xp-hunger: true
sync-player-effects: true

# Client (self) Host
host: '127.0.0.1'