name: WorldQLClient
version: 1.0
api-version: 1.18
main: com.worldql.client.WorldQLClient
softdepend: [PlaceholderAPI]
commands:
  unstuck:
    description: Get unstuck from a cave.
    usage: /unstuck
    permission: worldqlclient.unstuck
  mtp:
    description: Cross-server teleport.
    usage: /mtp <destination-player>
    permission: worldqlclient.mtp
  mtpa:
    description: Cross-server tpa (like Essentials)
    usage: /mtpa <destination-player>
    permission: worldqlclient.mtpa
  mtpaccept:
    description: Accept cross-server tpa (like Essentials)
    usage: /mtpaccept
    permission: worldqlclient.mtpaccept

permissions:
  worldqlclient.unstuck:
    default: false
    description: allow the usage of /unstuck
  worldqlclient.mtp:
    default: op
    description: Allows teleporting to players without their consent.
  worldqlclient.mtpa:
    default: true
    description: allow the usage of /mtpa
  worldqlclient.mtpaccept:
    default: true
    description: allow the usage of /mtpaccept
