name: WorldQLClient
version: 1.0
api-version: 1.16
main: com.worldql.client.WorldQLClient
softdepend:
  - WorldGuard
  - WorldEdit
commands:
  refreshworld:
    description: Pull and apply all block actions from database;
    usage: /refreshworld
    permission: worldqlclient.refreshworld
    
permissions:
  worldqlclient.refreshworld:
    default: op
    description: allow the usage of /refreshworld
