name: WorldQLClient
version: 1.0
api-version: 1.16
main: com.worldql.client.WorldQLClient
commands:
  spawnghost:
    description: Test player ghost functionality.
    usage: /spawnghost
    permission: worldqlclient.spawnghost
  stepghost:
    permission: worldqlclient.

depend: [ProtocolLib]