name: Java Build
on:
  push:
    branches:
      - trunk
  pull_request:

env:
  JDK_VERSION: '17'
  SPIGOT_VERSION: '1.18'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ env.JDK_VERSION }}
    - name: Cache Maven Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Compile Spigot with BuildTools
      uses: SpraxDev/Action-SpigotMC@v3
      with:
        versions: ${{ env.SPIGOT_VERSION }}
        buildToolProvider: SpigotMC
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Resolve .jar name
      id: prep
      run: |
        JAR_PATH=`echo **/WorldQLClient-*[^shaded].jar`
        JAR_NAME=`basename ${JAR_PATH}`

        echo ::set-output name=jar_path::${JAR_PATH}
        echo ::set-output name=jar_name::${JAR_NAME}
    - name: Upload .jar
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.prep.outputs.jar_name }}
        path: ${{ steps.prep.outputs.jar_path }}
